M48
; DRILL file {KiCad 9.0.6} date 2025-12-23T13:53:11+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-23T13:53:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X163.06Y-58.565
X168.14Y-57.549
X168.14Y-59.581
T2
X130.6Y-21.6
X131.7Y-81.7
X196.7Y-67.2
X215.0Y-23.0
M30
